  
version: "3.4"
services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./SampleCollections:/usr/local/sampleCollections
    working_dir: /usr/local/sampleCollections

  db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - 5434:5432
    volumes:
      - db-data:/var/lib/postgresql/data:rw
  
  pgadmin:
    image: dpage/pgadmin4:4.18
    environment:
        PGADMIN_DEFAULT_EMAIL: root@linuxhint.com
        PGADMIN_DEFAULT_PASSWORD: password
        PGADMIN_LISTEN_PORT: 80
    ports:
      - "8081:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    links:
      - "db:pgsql-server"

  server:
    image: node:alpine3.10
    ports:
      - 3001:3000
    environment:
      PORT: 3000
      MONGO_URL: "mongodb://root:password@mongo:27017/app"
      DATABASE_URL: "postgres://root:password@db:5432/app"
      JWT_SECRET: "secret"
    volumes:
      - ./server:/home/node/app
    depends_on:
      - mongo
      - db
    working_dir: /home/node/app
    command: sh -c "npm install --no-update-notifier; npm start --no-update-notifier"

  client:
    image: node:alpine3.10
    ports:
      - 3000:3000
    environment:
      API_URL: http://localhost:3000
    volumes:
      - ./client:/home/node/app
    working_dir: /home/node/app
    command: sh -c "npm install --no-update-notifier; npm start --no-update-notifier"

  psp:
    image: node:alpine3.10
    ports:
      - 3003:3000
    environment:
      PORT: 3000
      API_URL: http://server:3000
    volumes:
      - ./psp:/home/node/app
    working_dir: /home/node/app
    command: sh -c "npm install --no-update-notifier; npm start --no-update-notifier"

volumes:
  db-data: {}
  pgadmin-data: {}